/*
    ESCOPO GLOBAL

    ESCOPO LOCAL

    - O ESCOPO DETERMINA A VISIBILIDADE DE UMA VARIÁVEL
    - AS FUNÇÕES NO JS CRIAM SEU PROPRIO ESCOPO
        - AS VARIAVEIS DE UMA FUNÇÃO NÃO SÃO ACESSIVEIS  FORA DELA

*/